[package]
name = "Rust_MCS"
version = "0.1.0"
edition = "2024"


[dependencies]
nalgebra = "*"


[dev-dependencies]
criterion = "*"
approx = "*"

[[bench]]
name = "benchmarks"
harness = false

# For cargo flamegraph --bench benchmarks
#[profile.release]
#debug = true