[package]
name = "Rust_MCS"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "*"
approx = "*"
itertools = "*"

[profile.release]
debug = true

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false